on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd python/ && make clean check all && cd ..
  pip:
    needs: [make]
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check pip installation
        run: |
          pip install https://api.github.com/repos/valab-certh/meddisc/tarball/main#subdirectory=python